name: Release

on: push

jobs:
  build-and-release-macos:
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
      MACOS_APP_NAME: BlockDownloader.app
      
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '2.10.4'

      - name: Install project dependencies
        run: flutter pub get

      - name: Enable macOS build
        run: flutter config --enable-macos-desktop

      - name: Build artifacts
        run: flutter build macos --release
      
      - name: Archive Release
        run: |
          cd ${{ env.MACOS_APP_RELEASE_PATH }}
          zip -r ${{ env.MACOS_APP_NAME }}.zip ${{ env.MACOS_APP_NAME }}

      - name: macOS Release
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ env.MACOS_APP_NAME }}
          path: ${{ env.MACOS_APP_RELEASE_PATH }}/${{ env.MACOS_APP_NAME }}.zip
