name: Release

on: push

jobs:
  build-and-release-macos:
    runs-on: macos-latest
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '2.10.4'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: BlockDownloader-${{ github.sha }}-macos.zip
          directory: ${{ env.MACOS_APP_RELEASE_PATH }}
          path: ${{ env.MACOS_APP_RELEASE_PATH }}/Block Downloader.app
      - name: macOS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.MACOS_APP_RELEASE_PATH }}/BlockDownloader-${{ github.sha }}-macos.zip
